### ISSUE TITLE
bumping findup-sync

### ISSUE THREAD

**Issue by tkellen** [js-cli/js-liftoff#54]
Whatcha think, @phated? Minor or major bump here for Liftoff?

**Comment by phated** [comment]
@tkellen we control all the lookups using findup-sync, correct?  No user input for globs?  And I am pretty sure none of our usage was reliant on globs breaking changes so we should be able to get away with a minor (unless I am mistaken on the 2 questions I asked).

**Comment by tkellen** [comment]
You're right, we can totally do this as a minor bump.
