### ISSUE TITLE
Any examples of completions being used?

### ISSUE THREAD

**Issue by callumlocke** [js-cli/js-liftoff#56]
I want to use the completions feature but it's barely documented and I can't work it out. Are there any examples I can look at?

**Comment by tkellen** [comment]
There sure are!

https://github.com/gulpjs/gulp-cli/tree/master/completion

**Comment by callumlocke** [comment]
nice

**Comment by tkellen** [comment]
It'd be awesome if you whipped up some samples for the [hacker](http://github.com/js-cli/js-hacker) project so other people could see this readily too!
