### ISSUE TITLE
Possibility to pass options to a compiler

### ISSUE THREAD

**Issue by mikehaas763** [js-cli/js-liftoff#57]
I would like to have the ability to pass options to a compiler. For example, with babel you can configure it like `require('babel-core/register')({options:{}})`. Is this already possible or if not, does it align with the design principles of this library?

**Comment by tkellen** [comment]
Do you mean that you as a CLI author want to control this, or you as a CLI user would like to be able to customize this when launching a tool that uses Liftoff?

**Comment by tkellen** [comment]
This is not currently possible, but I'm open to the idea that it should be.

For the case of a CLI author, you can override the prototype `requireLocal` [seen here](https://github.com/js-cli/js-liftoff/blob/master/index.js#L25-L33) right now. I'd be open to providing a better API into that functionality, though.

For the case of a CLI consumer customizing this via the command line, we can implement this, but Liftoff cannot do the options parsing, that's up to consumers of this library.

**Comment by mikehaas763** [comment]
> Do you mean that you as a CLI author want to control this, or you as a CLI user would like to be able to customize this when launching a tool that uses Liftoff?

I think both, if it can be done with Liftoff (which you mentioned you can in the 2nd reply) then I would assume it's up the the lib author to traffic cop the options if they want to have the feature in their lib. Does that sound like how it should be designed? I am actually wanting to do this through gulp as an FYI.

**Comment by phated** [comment]
Currently, a CLI author can pass their own options by passing a custom list of interpreters to Liftoff - see https://github.com/js-cli/js-interpret/blob/master/index.js#L5-L11

For your example, it is recommended you use a babelrc to specify custom options - see https://babeljs.io/docs/usage/babelrc/
