### ISSUE TITLE
Case sensitivity issue with most recent release

### ISSUE THREAD

**Issue by tkdan235** [js-cli/js-liftoff#72]
The [Gulp](https://github.com/gulpjs/gulp) project uses js-liftoff as a dependancy.  In the past couple of hours folks have been experiencing broken builds via Gulp.  See this issue: gulpjs/gulp#1697.

In my case, Gulp uses a file named `Gulpfile.coffee` for its configuration.  Today Gulp failed to load `Gulpfile.coffee`. After our team did some digging into the issue we found that by changing the file to `gulpfile.coffee` the issue was resolved.

So a heads up, case insensitivity appears to have regressed.

**Comment by phated** [comment]
This is a problem all the way down in findup-sync -> micromatch.  I've contacted @jonschlinkert

**Comment by jonschlinkert** [comment]
reviewing now

**Comment by jonschlinkert** [comment]
I just published a patch that should fix the issue. If someone could verify that would be awesome, and much appreciated

**Comment by phated** [comment]
@jonschlinkert do we need to add the `nocase` option to findup-sync or liftoff?

**Comment by phated** [comment]
nvm, liftoff has it already

**Comment by jonschlinkert** [comment]
sorry, to clarify basically there was a function where the `nocase` option wasn't being passed down. it was definitely a bug in micromatch.

**Comment by phated** [comment]
Rolled back the findup-sync upgrade until we fix it.  Published as 2.2.4
