### ISSUE TITLE
Add option to set cwd in `Liftoff` constructor

### ISSUE THREAD

**Issue by weswigham** [js-cli/js-liftoff#78]
This way the appropriate `cwd` can be set when all `register` hooks get hooked in. This is an issue in, for example, `gulp` when using `ts-node` in a subdirectory with `--cwd`. The `cwd` passed is not respected by the require hooks included by liftoff since the `cwd` is only set during `launch` (so it is not set when the `require` hook is loaded).

**Comment by phated** [comment]
The require hooks are loaded with node's `require` which doesn't take into account a `cwd` parameter and instead use `process.cwd()`.  Liftoff should not be responsible for changing that (although, gulp decides to do that in its CLI).  @tkellen do you agree?

**Comment by weswigham** [comment]
So the correct fix would instead be, in `gulp`, _before_ it's construction of `Liftoff`, using `process.chdir`?

**Comment by phated** [comment]
@weswigham that would be the only place where we'd consider it.  If you open an issue on gulp-cli, we can discuss over there.  It would effect this chunk of code: https://github.com/gulpjs/gulp-cli/blob/master/index.js#L131-L137

Closing this.

**Comment by tkellen** [comment]
Agreed @phated! If we wind up thinking this is a best practice, we should consider updating [hacker](https://github.com/js-cli/js-hacker) to  do it as well.
