### ISSUE TITLE
support package.json key

### ISSUE THREAD

**Issue by alexisvincent** [js-cli/js-liftoff#84]
Hey guys,

Great project :) Does pretty much everything I do manually and more. 

The only thing that I currently do that I wouldn't be able to with this project is,
check for a specified key in the `package.json` and use the object it maps to as config (if it exists). Similar to what babel does.

So for instance. I can config my cli utility either through a `systemjs-tools.js` file or a `systemjs-tools` key in package.json.

What would it take to support this?

**Comment by alexisvincent** [comment]
After a little bit of thought, I think that all that needs to happen would be to add a `filter` key to the `fined` config option. This would mean, when it discovers a file, it could pass the file path to the provided `filter` function. If the function returns `true` it is assumed to be the config file, and on false it moves on.

This would mean folks could do their own `package.json` checking and is a good general solution.

**Comment by phated** [comment]
I believe you can already implement that with the https://github.com/js-cli/js-liftoff#optsconfigfiles feature that @sttk added.  It would only require a little glue-code in your implementation.  Right @sttk?

**Comment by alexisvincent** [comment]
@phated Thanks for the response. But after reading the docs, I don't see how I would implement it.

**Comment by alexisvincent** [comment]
Oh I see, I was under the impression that it stopped once it found a file, but if it returns all the config files that conform to the rule that's diffirent

**Comment by tkellen** [comment]
:+1: to that. Also, Liftoff automatically provides the value of `package.json` for you under the `modulePackage` key. If you don't need a "non-standard" lookup path, you can use that. For example:
https://github.com/js-cli/js-hacker/blob/master/bin/hacker.js#L43

**Comment by tkellen** [comment]
That's done here:
https://github.com/js-cli/js-liftoff/blob/master/index.js#L91-L115
https://github.com/js-cli/js-liftoff/blob/master/index.js#L153

**Comment by sttk** [comment]
@phated Yes. But as @tkellen says, the full path and contents of `package.json` are already given as `env.modulePath` and `env.modulePackage`. It's easiler to use them.

**Comment by phated** [comment]
Thanks @tkellen and @sttk!  I'm going to close this.
