### ISSUE TITLE
Twice require messages when specifying v8flags

### ISSUE THREAD

**Issue by sttk** [js-cli/js-liftoff#90]
Same require message is outputted twice, when a config file needs a loader (ex. `hackerfile.babel.js`) and v8flags are given, as follows:

```sh
$ ls
hacker.js		node_modules/
hackerfile.babel.js	package.json
$ node hacker --harmony
Unable to load: @babel/register { [Error: Cannot find module '@babel/register' from '/Users/sttk/hacker'] code: 'MODULE_NOT_FOUND' }
Loading: babel-register
Detected node flags: [ '--harmony' ]
Respawned to PID: 90011
Unable to load: @babel/register { [Error: Cannot find module '@babel/register' from '/Users/sttk/hacker'] code: 'MODULE_NOT_FOUND' }
Loading: babel-register
```

To fix this issue, [this part](https://github.com/js-cli/js-liftoff/blob/master/index.js#L118-L130) should be moved to [here](https://github.com/js-cli/js-liftoff/blob/master/index.js#L203). (In addition, this modification will enable to configure logs for `require` and `requireFail` events!)

--
EDIT: I modified the range of moving part.

**Comment by phated** [comment]
There's a bunch of issues surrounding js-rechoir that I was digging into earlier this week.  I think this could be cleaned up with that stuff too.
