### ISSUE TITLE
please turn on travis CI for node.js 8

### ISSUE THREAD

**Issue by simevo** [js-cli/js-liftoff#96]
The current stable version of node.js is 8.11.1 - it could be worth updating the `.travis.yml` to test on node-js 8 ?

**Comment by phated** [comment]
Node 8 and 10 were added to the Linux and Windows matrix in https://github.com/js-cli/js-liftoff/commit/7853fd33d6f97c2abb5f81b7197736f0e0a1d971

OSX tests were also enabled in that commit.
